# Gems
gems: [jekyll-paginate]

# Dependencies
#markdown:         redcarpet
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title: Makkura's Project Portal
email: joseph.still@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An eclectic collection of code projects, snippets, and blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  makkura
tagline:          'Occasional code snippets'
#url:              
baseurl:          "/"
encoding:         utf-8

author:
  name:           'Joseph Still'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  #repo:           https://github.com/poole/hyde
