# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Makkura's Project Portal
email: joseph.still@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An eclectic collection of code projects, snippets, and blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: _makkura_
github_username:  makkura

# Build settings
markdown: kramdown

# Windows Configuration Settings via http://jekyll-windows.juthilo.com/
encoding: utf-8
highlighter: rouge
